name: mido-main

on:
  workflow_dispatch:

jobs:
  fussionbuild:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setting up env
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git make bc bison flex ccache \
            openssl curl zip kmod cpio \
            libelf-dev libssl-dev wget \
            device-tree-compiler \
            ca-certificates python3 \
            gcc-arm-linux-gnueabi \
            gcc-aarch64-linux-gnu \
            binutils-arm-linux-gnueabi \
            binutils-aarch64-linux-gnu

      - name: Building Kernel
        env:
          CHATID: ${{ secrets.CHATID }}
          API_BOT: ${{ secrets.BOT_API }}
        run: |
          chmod +x build.sh
          bash build.sh
